spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://g7622u.h.filess.io:3306/degen_db_nobodymain?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:degen_db_nobodymain}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:737c038c45e2ca0e2f699d2a7612d313efeb9d68}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect